version: "3.8"

services:
  singularity-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin1234
    depends_on:
      - postgres
    networks:
      - internal_net
    command: uvicorn singularity.server.server:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  adminer:
    image: adminer
    ports:
      - "9001:8080"
    networks:
      - internal_net

volumes:
  postgres_data:

networks:
  internal_net:
    driver: bridge
